### ISSUE TITLE
Admin actions

### ISSUE THREAD

**Issue by iho** [ababic/wagtailmodeladmin#1]
Hi @ababic !
It will by nice to have thing like this for mass objects deletions https://docs.djangoproject.com/en/1.8/ref/contrib/admin/actions/

**Comment by ababic** [comment]
Hi @iho. I had entertained implementing actions, but I decided against it part way through for the following reasons... 

Firstly, unlike django admin, you have a button for each row to delete items individually (if the user has sufficient permissions), which I think will be useful enough most of the time, and keeps the interface simpler and familiar to other parts of the wagtail CMS. 

Also, in the case of models extending Page,  because of wagtail's permission system, even with a list of object of the same type, the user could potentially have varying permissions accross the objects they selected, and that really needs to be respected and handled somehow. That brings with it its own set of questions, e.g. do you process some rows and not others, and provide feedback after? do you process none and say there's and issue beforehand? do you create some fancy ajax js to change the action select box to only show actions permitted for the current selection? Also, how do you know which actions require what permissions (for custom actions, it might not be obvious).

**Comment by iho** [comment]
I do not work with permissions system, so I do not know :)

I want use your fine list view use with https://gist.github.com/iho/f3b323984b248c36e350 
It beat tricky to understend what your code do.

**Comment by ababic** [comment]
Okay, you seem to be going for a full on set of management views, which is a little different from what this project was going for. 

From what we I understand of working with wagtail, most models you create are either a page (extending the Page model e.g. BlogPostPage), or are reusable snippets (e.g. testimonials or staff members, that only ever appear elsewhere on other pages), and registered as such. And when integrated into wagtail in the standard way, wagtail already provides all of the functionality you need to access and manage them. It's just a little tucked away and generic. 

All my code really does is provide functionality for the list page, and gives you callables to fit them into the menu and CMS. The editing/adding/deleting/ parts are already provided for pages and snippets (and the editing interface often already configured using wagtails various edit panels), so we link right into those and try not to reinvent the wheel.

There's also some stuff in there to make it respect a lot of page-related wagtail stuff (permissions / which pages can be added where) etc, but that's basically it. 

The code is based on django's ModelAdmin class (it did originally extend it, until I realised I was overriding more functionally than I was using),  and also django admin templates and template tags. That part of django is a bit fragmented by nature and difficult to adapt, so apologies for the sometimes untidy implementation/code. We just wanted to get it working for now, and focus on the tidying later :)

**Comment by ababic** [comment]
Unfortunately, because of the django-admin based implementation, the functionality is a little tricky to copy out and reuse, since it's broken up over the option classes themselves, the adapted ChangeList view, and template tags. I'm sure there's a much neater way of doing things, but it at least seems stable for now. Sorry I can't be of any more help!

**Comment by SalahAdDin** [comment]
:+1: Please, try to do this :D

**Comment by ababic** [comment]
Hi @SalahAdDin. I don't think I'm going to have time to do it on my own, unfortunately. Although, wagtailmodeladmin is now under review for inclusion into the Wagtail core, where it will benefit from input from lots more developers, with lots more time between them... so it may come eventually.
