### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by wide-awake** [ababic/wagtailmodeladmin#17]
The only icons you can use is
https://github.com/torchbox/wagtail/blob/master/wagtail/contrib/wagtailstyleguide/templates/wagtailstyleguide/base.html#L496-L568 

Maybe we can add Font Awesome in package?

**Comment by ababic** [comment]
It's reasonably easy to do this in your project by utilising the `insert_editor_css` hook provided by Wagtail, and adding your own CSS http://docs.wagtail.io/en/v1.1/reference/hooks.html#insert-editor-css

There are licensing issues attached to the usage of most icon fonts, so I didn't want to package anything up with `wagtailmodeladmin` itself. Also, I'd rather leave it open so that developers are free to use whatever they feel is best for their project.
